In [1]:
import numpy as np

In [96]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [3]:
mask = a < 0

In [5]:
#1
len(a[mask])

4

In [8]:
#2
len(a[a > 0])

5

In [99]:
#3
mask = (a % 2 == 0) & (a > 0)
len(a[mask])

3

In [98]:
#4
a_plus_3 = a + 3
len(a_plus_3[a_plus_3 > 0])

10

In [30]:
#5
a_sqrd = a ** 2
print(np.std(a_sqrd))
print(np.mean(a_sqrd))

144.0243035046516
74.0


In [35]:
#6
a_centered = a - np.mean(a)
a_centered
np.mean(a_centered)

0.0

In [37]:
#7
a_zscores = (a - np.mean(a)) / np.std(a)
a_zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [38]:
#8
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [60]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a= np.sum(a)
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.prod(a)
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
alist_sqrd = [x **2 for x in a]
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
a_array = np.array(a)
mask = a_aray % 2 == 0
odds_in_a = a_array[~mask]
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a_array[mask]

In [61]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [65]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
b = np.array(b)

sum_of_b = np.sum(b)

In [77]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = np.min(b)
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = np.max(b)
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = np.mean(b)
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = np.prod(b)
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = list(b**2)
# Exercise 7 - refactor using numpy to determine the odds_in_b
mask = b % 2 == 0
odds_in_b = b[~mask]
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = b[mask]
# Exercise 9 - print out the shape of the array b.
np.shape(b)
# Exercise 10 - transpose the array b.
np.transpose(b)
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.reshape(b,(1,6))
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [78]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [85]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
print(np.min(c))
print(np.max(c))
print(np.sum(c))
print(np.prod(c))
# Exercise 2 - Determine the standard deviation of c.
print(np.std(c))
# Exercise 3 - Determine the variance of c.
print(np.var(c))
# Exercise 4 - Print out the shape of the array c
print(np.shape(c))
# Exercise 5 - Transpose c and print out transposed result.
print(np.transpose(c))
# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c,c))
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
print(np.sum(c * np.transpose(c)))
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
print(np.prod(c* np.transpose(c)))

1
9
45
362880
2.581988897471611
6.666666666666667
(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
261
131681894400


In [86]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [102]:

# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)
# Exercise 4 - Find all the negative numbers in d
mask = np.array(d) < 0 
np.array(d)[mask]
# Exercise 5 - Find all the positive numbers in d
np.array(d)[~mask]
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)
# Exercise 7 - Determine how many unique numbers there are in d.
print(len(np.unique(d)))
# Exercise 8 - Print out the shape of d.
print(np.shape(d))
# Exercise 9 - Transpose and then print out the shape of d.
print(np.transpose(d).shap)
# Exercise 10 - Reshape d into an array of 9 x 2
print(np.reshape(d,(9,2)))

11
(3, 6)
(6, 3)
[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
